name: Test Pull Request

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  quick-test:
    name: Quick Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -e .
        python -m pip install pytest pytest-cov
    
    - name: Run quick tests
      run: |
        python -m pytest tests/ -v --tb=short
    
    - name: Test CLI
      run: |
        python -m text_fancipy show
        python -m text_fancipy bold -t "Hello World"
        echo "Hello World" | python -m text_fancipy bold | python -m text_fancipy undo

  validate-scripts:
    name: Validate Scripts
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    
    - name: Make scripts executable
      run: chmod +x scripts/*.py
    
    - name: Test build script
      run: |
        python scripts/build.py --python
    
    - name: Test test script
      run: |
        python scripts/test.py --unit